### ISSUE TITLE
x86_64 liblayout crashes in dynamic_cast

### ISSUE THREAD

**Issue by waddlesplash** [diversys/liblayout#3]
1. Build x86_64 WonderBrush2 (https://github.com/stippi/WonderBrush-v2/pull/2)
2. Try to run
3. Crashes on startup in a dynamic_cast within liblayout.

Possibly a WonderBrush bug, but the same code works on GCC7 32-bit...

**Comment by diversys** [comment]
I can send you source code if needed via email.

**Comment by waddlesplash** [comment]
Yes, I think that will be helpful.

**Comment by diversys** [comment]
WonderBrush doesn't crash anymore thanks to the recent fixes to liblayout done by Jerome!
