### ISSUE TITLE
x86_64 liblayout broken for HGroup and VGroup

### ISSUE THREAD

**Issue by korli** [diversys/liblayout#4]
Beam builds with a patch on x86_64, but only the first element of a VGroup or a HGroup is actually added to the layout. 

https://github.com/haikuports/haikuports/commit/5841f628860f3a9b57e5d9b931353fd781d602a0

**Comment by korli** [comment]
Beam builds OK with x86 gcc7 and x86 liblayout, so the issue is specific to x86_64.

**Comment by diversys** [comment]
Oh, cool! Beam builds here with gcc8 on x86_64 too with your patch. Do you have liblayout sources?

**Comment by korli** [comment]
No, I don't have the liblayout sources.

**Comment by diversys** [comment]
I rebuilt liblayout with your patch and then Beam and the problem remains.

**Comment by diversys** [comment]
Actually, it works! I simply forgot to install new liblayout package :)
